os: linux
language: python
python: "3.6"
git:
  depth: 2
services:
- docker
branches:
  only:
  - master
  - devel
env:
  global:
  - IMAGE=dddecaf/wsgi-base
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_TIMESTAMP=$(date --utc --iso-8601=seconds)
  - BUILD_DATE=$(date --utc --iso-8601=date)
before_install:
- echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin
- pip install cookiecutter
install:
- make build
script:
- ./.travis/test-alpine.sh
- docker run --rm ${IMAGE}:debian gunicorn --version
after_success:
- make push
notifications:
  email: false
  slack:
    rooms:
      secure: eCnjUreiZm3EZSqpeey6MCtbJgMfbzWLIL6hJqegFt/erV9hsfgUaGRDf0JWls6b1eNhVVgx7YBBpq5j9fhweBgH18dGlwU8BPMyqlixzwCiK2WHfJbZ7xaDtbONrVyS1RV2a4AHZNyiQUHaANkPLyaVIW/B63MxFB4smQsFKpDiYbYXCOwL5WF++V0bozXubbkxCxpG6coUVEiVbGFmYcnrReVjEzVaMTfjZjZez7xRHyCTgr5PLCtkHr85GkhrKI/qhYk5mUKR823L+N7RHNuv5d+sKkWq9arhLc7+yaaRXNfRM9+M2S2vXAyTvQJ81H5VbSOAUr9WisGvxUX5k3EvOxafKTeJBqwd7kbppSQyYu4J+UgK0vd1CV9zfo4BJQt9MzoUuEB1NNQi9q5BqNI0RuHUQXLFy5HtJxIxWnd06TuNvX3MGof8kJ554raRMJYYnRKgIat6RRbx2MY+NEGI93wfVMMSWhbjWWDECnVidaUKR1kDhedCXm80kvZ7US3PNDQVEmulXSyqc7EALXhiW0ds4xxBVyg56hHcNH8n63NE13Kf/XBe3TuM68FlYOyOIWmVyihOVcjNA2jyuRy/jR9P0tLRab7H+eGu7rVSpWR8eO1c8RTyEngJXSZP/ocfXe9mvSk5BYv5TH9SFvGUkHYRRDwZMUJTXXwOmO8=
    on_success: change
    on_failure: change
    on_pull_requests: false
